### ISSUE TITLE
Onboard new TOC members

### ISSUE THREAD

**Issue by maoo** [finos/technical-oversight-committee#105]
- [x] Close all Github issues related with voting
- [x] Notify new TOC members
- [x] Add new TOC members to toc@lists.finos.org
- [x] Add new TOC members to https://github.com/orgs/finos/teams/technical-steering-committee
- [x] Add new TOC members to https://github.com/finos/technical-oversight-committee readme (sent end term to 30 October 2025) - https://github.com/finos/technical-oversight-committee/pull/104
- [x] Add "welcome new members" in the next meeting's agenda
    - [x] Ask to volunteer for some of the items listed in [responsibilities.md](https://github.com/finos/technical-oversight-committee/blob/master/responsibilities.md)

**Comment by ColinEberhardt** [comment]
> set end term to 30 October 2025

Do we have a date for the end term for the others in the group?

**Comment by maoo** [comment]
> Do we have a date for the end term for the others in the group?

Given that the term for members who participated to the TOC pilot phase is one year, starting from the TOC board approval on July 19th 2023, the end term should be July 19th 2024.

**Comment by maoo** [comment]
Added new members to pending PR on https://github.com/finos/technical-oversight-committee/pull/104

**Comment by maoo** [comment]
All done here!
