### ISSUE TITLE
2023 Nov 22 - Technical Oversight Committee Meeting Minutes

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/technical-oversight-committee#107]
## Date
2023 Nov 22 - 17:00 (UTC)

### Zoom Info
- Meeting link: https://zoom.us/j/93181085065
- Meeting number: 931 8108 5065
- Password: Check the email invite
- Call-in: Find your local number https://zoom.us/u/abk6zPS0y5

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Backlog review - https://github.com/orgs/finos/projects/39
- [x] ???
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- @maoo led a discussion on the TOC responsibilities, covering
  - Solicit and recommend cross-project synergies
  - Establish technical and security standards, conventions and best practice
  - Review of project health
  - Review of project alignment with FINOS strategy
 - The TOC briefly discussed the above
 - It was noted that some of these are strategic, others are more BAU. For strategic responsibilities @mindthegab noted that the relationship between the TOC and Board may not be sufficiently mature for these to have an impact yet
 - The TOC agreed to concentrate on BAU activities in the short term, with strategic activities considered later in 2024 in order to feed into decisions for investment in the following year
 - All agreed that **Establish technical and security standards, conventions and best practice** and **Review of project health** were activities worth exploring later
 - It was noted that the intended frequency of these activities is very much a guide at this point
 - TOC members committed to exploring these responsibilities over the next 2 weeks ahead of further discussion at the next meeting
 - @mindthegab asked for volunteers to represent the TOC at the All Community Call next week, Elspeth kindly volunteered

## Action Items
- [ ] @maoo to facilitate further asynchronous discussion on **Establish technical and security standards, conventions and best practice** and **Review of project health** - perhaps GitHub issues?

**Comment by mindthegab** [comment]
Can we have 2m today to seek TOC participation (5m) and active promotion to the All Community call next week?

**Comment by maoo** [comment]
@maoo / FINOS

**Comment by ColinEberhardt** [comment]
@ColinEberhardt / Scott Logic

**Comment by rikoe** [comment]
@rikoe / Adaptive

**Comment by TheJuanAndOnly99** [comment]
@TheJuanAndOnly99 / FINOS

**Comment by jonfreedman** [comment]
@jonfreedman / Brevan Howard

**Comment by psmulovics** [comment]
@psmulovics / Morgan Stanley

**Comment by eminty69** [comment]
Elspeth Minty / RBC CM

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum @ Morgan Stanley

**Comment by psmulovics** [comment]
> Here's the link to the All Community Call - @finos/tsc if you can help us promote it it would be amazing - https://www.finos.org/hosted-events/2023-11-29-finos-all-community-call-q4-2023.

https://www.linkedin.com/pulse/finos-all-community-call-q4-2023-peter-smulovics-fpspe/

**Comment by ColinEberhardt** [comment]
https://www.linkedin.com/posts/colin-eberhardt-1464b4a_2023-11-29-finos-all-community-call-q4-2023-activity-7133348710461120514-IAIH?utm_source=share&utm_medium=member_ios
