### ISSUE TITLE
TOC support for strategic initiatives

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/technical-oversight-committee#109]
This is an issue to track assignment of TOC members to strategic initiatives. Please comment (or email @ColinEberhardt / TOC mailing list) to assign yourself to an initiative. The following is a list of initiatives with FINOS 'point of contacts' (R - responsible, S - supporting).

- FDC3 Interop (Existing) - Rob (R)
- Open Source Readiness (Existing) - Rob (R), Karl (S)
- Open RegTech (Existing) - Jane (R), PJ (S) - @stephengoldbaum 	
- CCC (Existing) - Rob (R),  Mao (S) - @eminty69 
- FS OSS Supply Chain - Gab (R), Mao (S) - @eminty69 
- Payments - Gab (R), Rimma (S) - @caradelia 
- AI / Open Financial LLM - Gab (R), Rimma (S) - @ColinEberhardt 
- Zenith - Rimma (R), Jane(S) - @brunodom 
- Educational / TraderX - Jane (S)	- @jonfreedman 
- Support model for FINOS projects - Jane (S) - @psmulovics 
- DEI - Rimma (R) - @psmulovics

**Comment by psmulovics** [comment]
I am happy to take DEI and support model - as I am involved in zenith & osr, I will excuse myself from them for clarity. @brunodom , can you take on Zenith?

**Comment by jonfreedman** [comment]
Having worked in a trading team as a user of a trading system and also having worked on building one I'm interested in TraderXCheersJon ---- On Thu,07 Dec 2023 20:31:37 -0500  ***@***.***  wrote ----
This is an issue to track assignment of TOC members to strategic initiatives. Please comment (or email @ColinEberhardt / TOC mailing list) to assign yourself to an initiative. The following is a list of initiatives with FINOS 'point of contacts' (R - responsible, S - supporting).

FDC3 Interop (Existing) - Rob (R)
Open Source Readiness (Existing) - Rob (R), Karl (S)
Open RegTech (Existing) - Jane (R), PJ (S)
CCC (Existing) - Rob (R),  Mao (S)
FS OSS Supply Chain - Gab (R), Mao (S)
Payments - Gab (R), Rimma (S)
AI / Open Financial LLM - Gab (R), Rimma (S) - @ColinEberhardt
Zenith - Rimma (R), Jane(S)
Educational / TraderX - Jane (S)
Support model for FINOS projects - Jane (S)
DEI - Rimma (R)

**Comment by ColinEberhardt** [comment]
Thanks everyone for nominating yourselves, I've updated the list to show who is assigned with what.

**Comment by brunodom** [comment]
> I am happy to take DEI and support model - as I am involved in zenith & osr, I will excuse myself from them for clarity. @brunodom , can you take on Zenith?

@psmulovics I am happy on taking on Zenith - please write my name down

**Comment by caradelia** [comment]
I can take Open Reg Tech and Payments

**Comment by stephengoldbaum** [comment]
Open Reg Tech for me

**Comment by rikoe** [comment]
I am happy to support FDC3 and CCC.

**Comment by epsstan** [comment]
I am interested in AI / Open Financial LLM. @ColinEberhardt - Do you have room for one more person ?

**Comment by brunodom** [comment]
@ColinEberhardt and @mindthegab  I think that I can be useful with the FS OSS Supply Chain as I have been on the [SLSA](https://slsa.dev/community#steering-committee) steering committee for the last 2+ years. I may help streamline it and make it go faster.
