### ISSUE TITLE
2023 Dec 20 - Technical Oversight Committee Agenda & Minutes

### ISSUE THREAD

**Issue by mindthegab** [finos/technical-oversight-committee#110]
## Date
20231220 - 9AM PST

### Zoom Info
(Wednesday Meeting)
- Meeting link: https://zoom.us/j/93181085065
- Meeting number: 931 8108 5065
- Password: Check the email invite
- Call-in: Find your local number https://zoom.us/u/abk6zPS0y5

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] TOC + Strategic Initiatives - status, next steps, which ones will be ready for presentation in Q1
- [ ] CCC + CFI (and cloud compliance initiative)
- [ ] OSS Supply Chain Security
- [ ] TOC OKRs in 2024
- [ ] Backlog review - https://github.com/orgs/finos/projects/39
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes
 - @mindthegab led a discussion on strategic initiatives.
 - Only those requiring central funding have to be proposed at Q1 board meeting. Initiatives which are self funded can be put forward at any time
 - A meeting to review all the strategic initiatives will held on 5th Jan, prior to the board meeting on the 17th.
 - The status of each initiative was discussed in turn.
 - A brief discussion on OKR's. TOC was asked to consider if it should be responsible for delivery on some of the 2024 goals.

**Comment by rikoe** [comment]
@rikoe / Adaptive

**Comment by eminty69** [comment]
Elspeth Minty / RBC CM

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by ColinEberhardt** [comment]
@ColinEberhardt / Scott Logic

**Comment by DamianReeves** [comment]
@DamianReeves / Capital One

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum @ Morgan Stanley

**Comment by brunodom** [comment]
Bruno Domingues @ Intel
