### ISSUE TITLE
2024 Jan 30 - Technical Oversight Committee Meeting Minutes

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/technical-oversight-committee#112]
## Date
2024 Jan 30 

### Zoom Info
- Meeting link: https://zoom.us/j/92917330824
- Meeting number: 929 1733 0824
- Password: Check the email invite
- Call-in: Find your local number https://zoom.us/u/aeyxSJfCnu

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Backlog review - https://github.com/orgs/finos/projects/39
- [ ] Discuss strategic initiatives
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes
 - OSR next steps - led by @psmulovics 
   - Q1 board meeting agreed to back throughout Q1, but leading into this being community-led in Q2
   - Peter is pushing to increase OSR SIG membership
   - member survey indicate early-stage commitment to leading these projects
   - A question was raised around whether it is OK for the SIG chair to also be TOC sponsor? Neither Peter or Colin (who are in this position) are concerned, but it does give an opportunity for more bandwidth / attentions
 - FDC3 - led by @rikoe 
   - backed from FINOS full year, predominantly by Rob
   - at the moment, little input (from Riko) is needed, but he could be called on if there are any technical challenges / disputes
 - Open RegTech (CDM and RegTech Council) - led by @stephengoldbaum 
   - they need public recognition of use / adoption to drive interest
   - without the solid use cases it is difficult to recommend technical solutions
   - a great opportunity to demonstrate FINOS projects working together
   - there are concerns about the readiness of this technology (JARs not in maven central)
   - at this point we also discussed whether FINOS needed an outreach committee, with guidance from the TOC. Or now, we'll perform outreach via the TOC sponsor / FINOS lead
 - CCC
   - possible changes in TOC leadership noted
 - DEI - led by @psmulovics 
   - goal is to make it part of our 'DNA'
   - trying to push activities more towards the membership
 - Climate - led by @caradelia 
   - further discussions required
 - AI readiness - led by @ColinEberhardt 
   - it was discussed whether this should this be member only? in Zenith, every second call is member only, which sounds like a good idea
 - Zenith - led by @psmulovics 
   - maturing a project to the point of making a case for funding a project
   - it is an incubator, POCs start in FINOS labs, when the graduate, they go through TOC

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by maoo** [comment]
@maoo / FINOS

**Comment by eminty69** [comment]
Elspeth Minty / RBC CM

**Comment by ColinEberhardt** [comment]
@ColinEberhardt / Scott Logic

**Comment by brunodom** [comment]
Bruno Domingues / Intel

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum @ Morgan Stanley

**Comment by jonfreedman** [comment]
@jonfreedman Brevan Howard

**Comment by rikoe** [comment]
@rikoe / Adaptive
