### ISSUE TITLE
2024 Feb 27 - Technical Oversight Committee Meeting Minutes

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/technical-oversight-committee#114]
## Date
2024 Feb 27 - time

### Zoom Info
- Meeting link: https://zoom.us/j/92917330824
- Meeting number: 929 1733 0824
- Password: Check the email invite
- Call-in: Find your local number https://zoom.us/u/aeyxSJfCnu

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Backlog review - https://github.com/orgs/finos/projects/39
- [ ] Update on strategic initiatives
- [ ] Discussion on TOC member 'cliff edge'
- [ ] Member and TOC KRs
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes
- We discussed the AI readiness group https://github.com/finos/community/issues/303
  - the notion of having a 'core team' is quite standard, and a model we'll adopt for this SIG
  - we need to clealry set out goals and direction from the get-go
  - @psmulovics offered support and the contribution of assets from Zenith
- We discussed the FINOS information architecture, it was noted that W3C has a standard approach to their various websites
   - At the moment FINOS microsites differ significantly
   - there is some work taking place at the moment https://github.com/finos/FDC3/pull/1151   
- We discussed the term of various TOC members, and that 10 of us have end dates that are aligned
  - @ColinEberhardt volunteered to 'shake the tree' a little, see if any TOC members wish to free up their seat early
- We discussed board KRs and their linkage to the TOC
  - @mindthegab will share the details with the group via the private email distro

**Comment by ColinEberhardt** [comment]
@ColinEberhardt / Scott Logic

**Comment by maoo** [comment]
@maoo / FINOS

**Comment by brunodom** [comment]
Bruno Domingues / Intel

**Comment by caradelia** [comment]
Cara Delia / Red Hat

**Comment by eminty69** [comment]
Elspeth Minty / RBC

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum @ Morgan Stanley

**Comment by DamianReeves** [comment]
Damian Reeves / Capital One
