### ISSUE TITLE
TOC Voting and elections

### ISSUE THREAD

**Issue by maoo** [finos/technical-oversight-committee#117]
10 out of 12 TOC seats are up for election on July 19th , see https://github.com/finos/technical-oversight-committee?tab=readme-ov-file#membership

This issue is a placeholder to decompose and track activities related with the election and voting process.

**Comment by maoo** [comment]
@ColinEberhardt - are there any seats that should be freed ahead of the voting in July ?

**Comment by ColinEberhardt** [comment]
> @ColinEberhardt - are there any seats that should be freed ahead of the voting in July ?

No, all members are either quite active, or have not indicated that they wish to release their seat.

**Comment by maoo** [comment]
> > @ColinEberhardt - are there any seats that should be freed ahead of the voting in July ?
> 
> No, all members are either quite active, or have not indicated that they wish to release their seat.

Thanks @ColinEberhardt .

As we have 10 seats (out of 12) that are up for elections in July (5 from the Board and 5 from the TOC), it would be good to stagger a bit and avoid that we have 10 new TOC members joining at the same time.

What if we plan the elections of the 5 seats from the TOC in May (ie 3rd week, so we have time to socialize it and gather candidacies) and the 5 seats from the Board in July?

**Comment by rikoe** [comment]
Why don't we vacate some seats at the end of May (e.g. 5), then the board can select some new members, and they (together with Peter and Damian) can then vote for the other new TOC members in mid-July as their first act of duty?

I am happy to put my hand up for vacating my seat early ✋.

**Comment by stephengoldbaum** [comment]
I'll put up my hand too

**Comment by jonfreedman** [comment]
I'd discussed with Colin the additional workload I've got right now, I'm also happy to release my seat. I think it's important for the membership to move to a close to 50/50 split on new elections so there is some continuity

**Comment by ColinEberhardt** [comment]
I'm very happy with this approach, good idea 👍

**Comment by epsstan** [comment]
> @ColinEberhardt - are there any seats that should be freed ahead of the voting in July ?

@maoo - I am happy to vacate my seat early
