### ISSUE TITLE
2024 April 10 - Technical Oversight Committee Meeting Minutes meeting

### ISSUE THREAD

**Issue by maoo** [finos/technical-oversight-committee#118]
## Date
2024/04/10

### Zoom Info
- Meeting link: https://zoom.us/j/92917330824
- Meeting number: 929 1733 0824
- Password: Check the email invite
- Call-in: Find your local number https://zoom.us/u/aeyxSJfCnu

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] TOC OKRs
- [ ] Cleanup (@maoo)
  - Added meeting minutes links into README - https://github.com/finos/technical-oversight-committee/issues/103
  - Updated FINOS TOC team in Github - https://github.com/orgs/finos/teams/toc
  - Raised issue for TOC voting - https://github.com/finos/technical-oversight-committee/issues/117
- [ ] Backlog review - https://github.com/orgs/finos/projects/39
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes
- Calendar issue:
  - sent out invite with EST timezone
  - Peter reports that the Wednesday meeting (remember that Tuesday meetings happen at 11.30am EST) still shows up at the wrong time (11am EST, instead of 12pm EST)
  - Mao and Juan to review Google notification
- Question: how do we go about assigning responsibilities across the TOC team?
  - Peter: for TOC member wearing other hats, look for alignment
  - Olivier: choose a lead for each responibility
  - Damian: can help on everything that is related to Morphir

## Action Items
- [ ] Discuss responsibilities on next meeting
- [ ] Discuss TOC voting on next meeting
- [ ] Work on calendar issue

**Comment by psmulovics** [comment]
I am in the zoom waiting room?

**Comment by ColinEberhardt** [comment]
ditto!

**Comment by brunodom** [comment]
Also, waiting the host to start the meeting.

**Comment by psmulovics** [comment]
@maoo ?

**Comment by maoo** [comment]
The meeting is at 12pm EST, and it shows fine on my calendar (in 38 minutes).

**Comment by DamianReeves** [comment]
Damian Reeves / Capital One

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by stephengoldbaum** [comment]
Sorry, the time zone issue threw me off, too.

**Comment by psmulovics** [comment]
Re-downloaded calendar - now it is ok.
