### ISSUE TITLE
2024 Jun 05 - Technical Oversight Committee Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/technical-oversight-committee#123]
## Date
20240605 - 11.30pm EST

### Zoom Info
[https://zoom.us/j/93181085065](https://www.google.com/url?q=https://zoom.us/j/93181085065&sa=D&source=calendar&ust=1718007341255470&usg=AOvVaw0UlHNuWTDTedNsM0SAjI7g)

Meeting ID: 931 8108 5065
Passcode: 331179
Call-in: Find your local number https://zoom.us/u/aeyxSJfCnu

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] [Tentative] AWS team presenting [HTC Grid project contribution](https://github.com/finos/community/issues/318)
- [ ] (optional) Approve past meeting minutes
- [ ] (optional) Backlog review - https://github.com/orgs/finos/projects/39
- [ ] AOB, Q&A & Adjourn (5mins)

## Past action Items
- [ ] ...

## Action Items
- [ ] ...

**Comment by PaulaPaul** [comment]
Hello @maoo, @ColinEberhardt  - I am interested in hearing more about the HTC Grid project; would it be possible to sit in on this TOC call as a guest (or will a recording be shared)?

**Comment by mindthegab** [comment]
Yes, the TOC meetings are open to the public if you want to join @PaulaPaul. Actually I think it would make sense to have them listed in the [FINOS Calendar](https://www.finos.org/calendar) - if @ColinEberhardt agrees, maybe @TheJuanAndOnly99 can operationalize this?

**Comment by rikoe** [comment]
Riko / Adaptive

**Comment by caradelia** [comment]
Cara Delia / Red Hat

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum @ Morgan Stanley

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley
