### ISSUE TITLE
[TOC Candidacy] Vincent Caldeira

### ISSUE THREAD

**Issue by caldeirav** [finos/technical-oversight-committee#124]
### Affiliation
Red Hat

### Biography
Vincent Caldeira serves as the Chief Technology Officer for Red Hat Asia Pacific & Japan, where he is responsible for forging high-impact partnerships with key strategic customers, and ultimately helping to shape the company's technological vision and strategy. Recognised as one of the 'Top 10 Chief Technology Officers in APAC' by Technology Magazine in 2023, Vincent brings over two decades of experience in the IT industry, including a proven track record for leading ambitious business and technology transformation roadmaps within the Financial Services industry. Vincent is not only an influential thought-leader in open source solutions, cloud computing, and digital transformation, but also a sought-after speaker at industry events, dedicated to fostering innovation and advocating emerging technologies in domains such as Modern Data Analytics, AI/ML, Digital Sovereignty and Information Technology Sustainability. Notably, Vincent has led the company's technology contributions in environmental sustainability, serving as the chief architect and Technical Advisory Council Chair for OS-Climate, a Linux Foundation-backed open source project. His leadership in this project demonstrates his commitment to integrating the impacts of climate change into global financial decision-making and risk management, showcasing his broad expertise and influence in the intersection of technology, policy, and sustainable development. More recently, Vincent has been leading Red Hat's global strategic initiatives in the realm of Digital Sovereignty, with a focus on open and interoperable standards, data federation architecture and governance, and partner ecosystem development, aligning with the growing needs for digital sovereignty in the Asia Pacific region.

### Reasons for candidacy
With the planned onboarding of OS-Climate as a Supplemental Directed Fund (SDF) under FINOS, my primary focus is to provide technical continuity to the initiatives currently running in the OS-Climate community and also visibility to the FINOS community for awareness and potential synergies. We have also identified that the [Data Commons](https://os-climate.org/data-commons/) stream currently under OS-Climate has the potential as a platform to provide immediate capabilities and synergies to other FINOS streams such as the Open RegTech initiative. I have already been engaging with members of the Open RegTech initiative on the technical design and architecture space and we have confirmed in-principle Red Hat technical contribution to this stream.

In addition, leveraging both my current role within Red Hat global engineering as well as my previous professional background in banking, I am happy in the near future to extend my contribution and cover Red Hat potential engagements across the FINOS community, included but not limited to:

1. AI Readiness SIG
2. Common Cloud Controls
3. InnerSource SIG (as a practitioner and recent member and contributor to the InnerSource Commons community)

**Comment by maoo** [comment]
Congratulations @caldeirav  , you've been selected to be part of the FINOS TOC. Looking forward to meeting tomorrow for your first TOC call.
