### ISSUE TITLE
[TOC Candidacy] John Arroyo

### ISSUE THREAD

**Issue by arroyo** [finos/technical-oversight-committee#127]
## Affiliation
Citi

## Bio
John Arroyo is a seasoned technologist with over 25 years of experience in software engineering, architecture, and team leadership. As the current Head of Developer Pipelines (Wealth, USPB, Functions) at Citigroup Inc. in Irving, TX, he oversees teams, focusing on CI/CD, resilience, performance engineering, and test engineering. His strategic management has significantly boosted productivity and reduced defects across the company’s development pipelines.

Previously, John served as the Chief Architect and Vice President at Entertainment Partners in Burbank, CA, where he spearheaded the design and implementation of complex systems. This included a new app store, subscription billing, and licensing systems integrated with IAM, Apigee and OPA.

John holds an M.S. in Electrical Engineering from Columbia University, an M.A. in Electro-Acoustic Music from Dartmouth College and a B.S. in Electrical and Computer Engineering from Carnegie Mellon University. His academic background includes advanced studies in software engineering, DSP, machine learning, artificial intelligence, and even algorithmic music composition.

An active participant in the tech community, John is a member of the Forbes Technology Council and supports various foundations including The Linux Foundation and the OpenJS Foundation. He was active for years with Southern California meetups and tech communities including running the LA Golang meetup. He currently lives near Dallas, Texas and dedicates free time to his homelab for open source and mentoring emerging tech talent through various volunteer positions and speaking engagements.

## Reasons for candidacy
If elected I would be an ambassador of and servant leader for FINOS. I would open up my network both professional and personal in support of the foundation. At Citi I have multiple venues to spread awareness of the FINOS projects. I would like to engage with specific projects and use my background to contribute to them as well as broaden open source usage within the bank.

I have been deeply involved in multiple open source communities in the past, including running meetups, presenting at conferences and of course contributing code and doing pull requests. It would be exciting to get more involved in these activities in the financial sector. It is something I have been looking forward to since joining Citi. I also look forward to finding more opportunities to contribute to projects like CCC, AI Readiness, and VUU. I can engage my team in the special interest groups as well. DevOps automation, Architecture as Code, and Open Source Readiness are concepts very important to us.

**Comment by maoo** [comment]
Thank you for the submission @arroyo !
