### ISSUE TITLE
[TOC Candidacy] <Stepan Pushkarev>

### ISSUE THREAD

**Issue by Yaroslavtarasyuk** [finos/technical-oversight-committee#129]
**Affiliation:** Provectus

**Bio:** 
Stepan Pushkarev is a public speaker, author, Co-founder, CTO and CEO of Provectus. He brings deep expertise in machine learning, cloud computing, and distributed data processing systems, as well as a successful track record of building professional services businesses and founding SaaS startups. At Provectus, Pushkarev spearheads the vision for industry-specific AI solutions that help businesses reimagine the way they operate, compete, and deliver customer value.
[LinkedIn profile](https://www.linkedin.com/in/stepanpushkarev/).

**Reasons for candidacy:**
An active contributor to the open-source community with deep technology expertise and industry knowledge gained through real-world collaboration with diverse Financial Services customers. 

**Public speaking sessions and interviews:**
Amazon re:MARS 2022 https://youtu.be/c1gBaI0BY50 
theCUBE at Amazon re:MARS 2022 https://www.youtube.com/watch?v=vy6fcG_5-vY 
re:MARS 2019 https://youtu.be/NhCgxUlosbE 
ODSC West 2018 https://www.youtube.com/watch?v=kvXJUZPlvto
Scale By The Bay 2018 https://www.youtube.com/watch?v=aRU2M1DReig 
Scale by the bay 2017 https://www.youtube.com/watch?v=2kmZbrr7yw4
ODSC East 2018 https://youtu.be/4M_3oZlc2B4 
ODSC Webinar https://www.youtube.com/watch?v=FBXP15AiGHA
Cloud Expo Santa Clara 2017 https://www.youtube.com/watch?v=-nqK2NkbdpU 
OReilly Software Architecture Conference 2017 London

**Comment by maoo** [comment]
Thanks for your candidacy Stepan!

**Comment by maoo** [comment]
This first round of voting closed today; next and round is scheduled for 6 September 2024.

**Comment by maoo** [comment]
Thanks for your candidacy Stepan ! We've started the voting today, and we are expecting to know the results by next week; we will keep you posted.

**Comment by TheJuanAndOnly99** [comment]
Dear Stepan thank you for your candidacy. We appreciate you taking the effort and initiative to put yourself forward for this position. Unfortunately you that you have not been selected to join the TOC this time around. We will be having another round of elections next year and we hope that you will consider putting your name in again. Thank you.
