### ISSUE TITLE
[TOC Candidacy] <Manuel Martos>

### ISSUE THREAD

**Issue by manel-martos** [finos/technical-oversight-committee#131]
Affiliation: TradeHeader

Bio:
Manuel Martos is the Chief Technology Officer at Tradeheader, a global consulting firm specializing in financial standards, training and software development. With over a decade of experience in the industry, Manuel has held various tech leadership roles where he successfully implemented innovative solutions to drive business growth and enhance operational efficiency for the industry participants.
Mr. Manuel received his Telecommunication Engineer Degree from the Universitat Politècnica de Catalunya in Barcelona.
[LinkedIn](https://www.linkedin.com/in/mmartosth/) 

Reason for candidacy:
Active contributor to the CDM and Rune DSL projects with deep technology and financial standards expertise, including work and participation in ISDA DRR, FpML, FIX, and ISO 20022. Manuel has also been involved in financial data quality, modelling, and data transformation projects.

**Comment by maoo** [comment]
Thanks for your candidacy @manel-martos

**Comment by maoo** [comment]
This first round of voting closed today; next and round is scheduled for 6 September 2024.

**Comment by maoo** [comment]
Thanks for your candidacy @manel-martos ! We've started the voting today, and we are expecting to know the results by next week; we will keep you posted.
