### ISSUE TITLE
[TOC Candidacy] <Elspeth Minty>

### ISSUE THREAD

**Issue by eminty69** [finos/technical-oversight-committee#139]
Affiliation:
RBC Capital Markets

Bio:
Elspeth is a Managing Director at RBC Capital Markets in Montreal.  She has worked in the financial industry for more than two decades. Her experience covers everything from developing core C++/Java libraries to helping teams adopt cloud technologies. She has worked in a number of locations, including London, Shanghai and Montreal. In her current role in RBC Capital Markets Elspeth is helping to improve code re-use and consistent application design by promoting an Inner Source approach. Elspeth has spoken at a range of technology conferences including QCon London and Shanghai, Spring One and the InnerSource Commons gathering.

Elspeth has a BSc in Physics from the University of Manchester, an MSc in Parallel Computer Systems from the University of West of England and a PhD in Cosmology from the University of Edinburgh.

[LinkedIn](https://www.linkedin.com/in/elspeth-minty/)

Reasons for candidacy
Elspeth has been an advocate for Open Source in the finance industry for a number of years, speaking at a number of forums on Open Source, InnerSource and FINOS.  She is a former member of the Governing Board at FINOS and is currently a member of the TOC. Elspeth has been a co-lead of both the InnerSource and Open Source Readiness SIGs.

**Comment by maoo** [comment]
Thanks for your candidacy @eminty69 ! We've started the voting today, and we are expecting to know the results by next week; we will keep you posted.

**Comment by TheJuanAndOnly99** [comment]
Congratulations @eminty69 you've been re-elected to stay on the FINOS TOC for a second term!
