### ISSUE TITLE
2024 Sep 25 - Technical Oversight Committee Meeting Minutes

### ISSUE THREAD

**Issue by TheJuanAndOnly99** [finos/technical-oversight-committee#142]
## Zoom Info
(Wednesday Meeting)
- Time: 12pm EST
- Meeting link: [https://zoom.us/j/93181085065](https://zoom.us/j/93181085065?pwd=cys5NHRqcWFZaG9qdlB4SlR2Zjh3UT09)
- Meeting id: 931 8108 5065
- Call-in: Find your local number https://zoom.us/u/abk6zPS0y5

(Tuesday Meeting)
- Time: 11.30am EST
- Meeting link: [https://zoom.us/j/92917330824](https://zoom.us/j/92917330824?pwd=WWlTRWk5bzkyZUZPZi9OZll5SVM0UT09)
- Meeting id: 929 1733 0824
- Call-in: Find your local number https://zoom.us/u/aeyxSJfCnu

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] openGRIS presentation (new project contribution from Citi - https://github.com/finos/community/issues/326)
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes
- [ ] @eminty69 will be the official TOC representative for the OpenGRiS contribution.
- [ ] ...
- [ ] ...

## Action Items
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by chris-twiner** [comment]
Chris Twiner (will join via mobile)

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by caldeirav** [comment]
Vincent Caldeira / Red Hat

**Comment by caradelia** [comment]
Cara Delia / Red Hat

**Comment by brunodom** [comment]
Bruno Domingues / Intel
