### ISSUE TITLE
[TOC Candidacy] <Flamur Gogolli>

### ISSUE THREAD

**Issue by fgogolli** [finos/technical-oversight-committee#144]
### Affiliation
Amazon Web Services (AWS)

### Bio
Flamur Gogolli is a Senior Specialist Solutions Architect at Amazon Web Services (AWS) focusing on helping Financial Services customers with their modernisation and digital transformation journey, from designing and building complex infrastructures to running large scale workloads efficiently. Prior to joining AWS, Flamur was a Vice President at JP Morgan & Chase, leading the cloud native transformation and migration of their Core Risk & Trade Management platform into public cloud. He brings over two decades of deep technical expertise working in several lead roles encompassing cloud, containers, DevOps, consulting and systems engineering across multiple countries and industries. Flamur speaks regularly at numerous confernces incl. Open Source in Finance Forum, Kubernetes Community Days, AWS Summits & Conferences, internal & external round tables, panels and events.

Flamur has a BSc in Computer Science & Engineering from the University of Business and Technology in Kosovo.

[LinkedIn](https://www.linkedin.com/in/flamurgogolli/)

### Reasons for candidacy
Flamur is one of the core contributors and maintainers of the [HTC-Grid](https://github.com/finos/htc-grid) Project.

Moreover, Flamur has long been an active member of the open source community, by contributing to other CNCF and OSS projects, speaking at and attending open-source conferences, and other community events and meetups. He has also created and led internal communities at JPMC and AWS, championing and advocating open source and cloud native technologies.

### Public Speaking
- [Open Source in Finance Forum - New York 2024](https://osffny2024.sched.com/event/1i6v0/building-and-running-an-hpc-grid-using-cloud-native-services-flamur-gogolli-kirill-bogdanov-amazon-web-services-aws?iframe=no)
- [ActiveViam Connect 2024: Panel Discussion on Cloud Implementation](https://fintech.activeviam.com/connect-london-2024)
- [Kubernetes Community Days - UK 2023](https://www.youtube.com/watch?v=sBjvOTRIKBQ&t=2s&ab_channel=KubernetesCommunityDaysUK)
- [Kubernetes Community Days - Oslo 2024](https://community.cncf.io/events/details/cncf-kcd-norway-presents-kcd-oslo-2024/)
- [Meet the Innovators: an exclusive roundtable for Capital Markets Quants](https://meettheinnovators.splashthat.com/)
- [DXC Luxoft & Orchestrade Capital Markets Digital Transformation Events in London and Zurich](https://www.linkedin.com/feed/update/urn:li:activity:7085208594513608704?utm_source=share&utm_medium=member_desktop).
- AWS Events in [Amsterdam](https://aws-experience.com/emea/north/e/90462/karpenter-amazon-eks-best-practices-and-cloud-cost-optimization), [Stockholm](https://aws-experience.com/emea/north/e/ababe/graviton-developer-day-for-python-go-and-java) and [London](https://aws-experience.com/emea/uki/e/80d85/graviton-developer-day).
- [JAMF Nation Live 2023 in London, Amsterdam & Paris](https://www.jamf.com/events/jamf-nation-live-london-2023/).

**Comment by maoo** [comment]
Thanks for your candidacy @fgogolli  ! We've started the voting today, and we are expecting to know the results by next week; we will keep you posted.

**Comment by TheJuanAndOnly99** [comment]
Congratulations @fgogolli, you've been selected to be part of the FINOS TOC. Looking forward to meeting at the next TOC call. You should have already gotten an email from me. If you have not please email help@finos.org! Thank you!
