### ISSUE TITLE
[TOC Candidacy] <Trevor O'brien>

### ISSUE THREAD

**Issue by sergio-gago-moodys** [finos/technical-oversight-committee#147]
Affiliation:
Moody's

Bio:
Trevor is a Senior Director Engineering @Moody’s, based in London. He currently leads the development efforts behind Moody’s first InnerSource initiative, a Gen AI innovation platform, open to the entire company, that powers several internal and external use cases. He also leads Moody’s efforts in the Blockchain and DeFi space, recently launching Moody’s first DeFi product, an AI tool that monitors risks associated with stablecoins. Trevor previously led development initiatives for several global brands including Volkswagen, where he led the launch of their global consumer platform, [vw.com](http://vw.com/) as well as their first ‘connected car’ mobile app.
In the earlier part of his career, he was the lead engineer of a digital content distribution system that synchronized real-time news with dynamic video files and templates, which was deployed by global banking and financial organizations. Trevor was also the first engineer and CTO for EON, where he developed an RFID based global system for textile recycling, which won H&M's annual Global Change Award and was subsequently awarded with various development grants.
Trevor holds a BSc Computer Science from Greenwich University and an MBA from the Berlin School of Creative Leadership and was awarded a Global Change Award for (https://fashionunited.com/news/fashion/previous-key-winners-from-the-h-m-foundation-s-global-change-award/2018030920142)

[LinkedIn](https://www.linkedin.com/in/trevorobrien/)

Reasons for candidacy
Through leading the InnerSource Gen AI initiative product and development teams at Moody’s Trevor has gained valuable experience in the establishment of compliance, governance, technology and architecture processes and committees to enable open source concepts at the enterprise level, specifically but not limited to the finance industry.

**Comment by maoo** [comment]
Thanks for your candidacy Trevor! We've started the voting today, and we are expecting to know the results by next week; we will keep you posted.

**Comment by TheJuanAndOnly99** [comment]
Dear Trevor thank you for your candidacy. We appreciate you taking the effort and initiative to put yourself forward for this position. Unfortunately you that you have not been selected to join the TOC this time around. We will be having another round of elections next year and we hope that you will consider putting your name in again. Thank you.
