### ISSUE TITLE
[TOC Candidacy] Andrew Aitken

### ISSUE THREAD

**Issue by psmulovics** [finos/technical-oversight-committee#148]
# Affiliation

Individual contributor at FINOS, former Global Open Source Leader at Wipro, Chief Open Source Officer at Hedera, twice Elected Board Member for FINOS Board of Directors, Board Observer for OpenSSF, Elected Member of the Board of the Linux Foundation Networking project.

# Bio

I am a seasoned expert in the art of creating open source-related ecosystems and communities that align the needs of the business and the developer. I have pioneered numerous open source strategies and business models; I have enabled organizations to harness the power of open source technologies to drive innovation, enhance governance, and foster collaborative ecosystems. With over two decades of experience advising global enterprises and startups, I provide strategic guidance on open source adoption, community engagement, cybersecurity, and governance. I empower organizations to leverage open source as a competitive advantage to drive innovation, sustainable growth and operational efficiency. I was the founder of the industry's only "think tank" on the future of open source, a bi-annual event held in Napa, CA, and Paris, France, for 10 years and regularly attended by leading CEOs and visionaries. 

I have advised the U.S. White House on open source and procurement policies, served as an expert witness on open source for the California Senate, and have been an invited guest lecturer at Stanford's Entrepreneur program. I have chaired and spoken internationally at multiple industry conferences, am a board member of FINOS, past board member of LF Networking and OSEHRA, and have personally worked with companies such as IBM, Microsoft, Intel, LBG, and the U.S. Navy.

Specialties: Open Source expertise; business and strategy consulting, sales, marketing, and business development

**Comment by maoo** [comment]
Thanks for your candidacy Andrew ! We've started the voting today, and we are expecting to know the results by next week; we will keep you posted.

**Comment by TheJuanAndOnly99** [comment]
Congratulations Andrew, you've been selected to be part of the FINOS TOC. Looking forward to meeting at the next TOC call. You should have already gotten an email from me. If you have not please email help@finos.org! Thank you!
