### ISSUE TITLE
[TOC Candidacy] - Martin Traverse

### ISSUE THREAD

**Issue by martin-traverse** [finos/technical-oversight-committee#149]
# Affiliation

finTRAC (Fintech startup)
CTO & co-founder
Starting November 2024
 
# Bio

Martin is a Technical Architect with 15 years’ experience consulting across the Finance industry. He specialises in large scale data & analytic platforms typically found in Risk, Finance & Treasury and has advised senior architects across the industry on modern patterns in this space. He is also a hands-on developer with in-depth knowledge of the data formats, network protocols and cloud stacks that support modern analytic solutions and has built several risk engines during his career. As a culmination of this work, he used his experience to design and build a new generation of model platform which solves most of the common problems typically encountered in this space, that platform became the TRAC solution which is now part of the FINOS foundation.
 
Martin spent most of his career working for specialist consultancies and has recently been at Accenture as the result of an acquisition. In November he will become CTO and co-founder of a fin-tech firm, which is building a commercial product based on the open-source TRAC solution. Martin was briefly involved in the FINOS TOC when it was first convened, however at the time this conflicted with his day job. Now with his own firm he is keen to involve both himself and his company in the open-source initiative!
 
# Reasons for candidacy

Martin has extensive with experience with real world application of technology in enterprise, including the technology itself, the development processes that surround it and the challenges that occur in real-world scenarios. He is an ardent believer in open source as a driver of efficiency, quality and standardisation, and with his new role he will bring a different perspective to the table.

**Comment by maoo** [comment]
Thanks for your candidacy @martin-traverse ! We've started the voting today, and we are expecting to know the results by next week; we will keep you posted.

**Comment by TheJuanAndOnly99** [comment]
Dear @martin-traverse thank you for your candidacy. We appreciate you taking the effort and initiative to put yourself forward for this position. Unfortunately you that you have not been selected to join the TOC this time around. We will be having another round of elections next year and we hope that you will consider putting your name in again. Thank you.
