### ISSUE TITLE
2024 Dec 3 - Technical Oversight Committee Meeting Minutes

### ISSUE THREAD

**Issue by psmulovics** [finos/technical-oversight-committee#164]
## Zoom Info
- Time: 11.30am EST
- Meeting link: [https://zoom.us/j/92917330824](https://zoom.us/j/92917330824?pwd=WWlTRWk5bzkyZUZPZi9OZll5SVM0UT09)
- Meeting id: 929 1733 0824
- Call-in: Find your local number https://zoom.us/u/aeyxSJfCnu

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] @eddie-knight - Introduce @mcderk to share about the LFX tooling
- [x] @eminty69 - Discuss Liaison Kickoff strategy
- [x] @chris-twiner - Discuss project lifecycle goals
- [x] @jgavronsky - FINOS Strategic Initiatives walkthrough
- [x] Backlog review - https://github.com/orgs/finos/projects/39
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- [ ] ...
- [ ] ...
- [ ] ...

## Action Items
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by eddie-knight** [comment]
:wave: :shipit: Eddie Knight / Sonatype

**Comment by eminty69** [comment]
Elspeth Minty / RBC

**Comment by awaiken** [comment]
ola

**Comment by chris-twiner** [comment]
Chris

**Comment by opoupeney** [comment]
Olivier / Finos

**Comment by psmulovics** [comment]
@mcderk presentation on LFX tooling
 * information about events, meetings, etc
 * Insights is the analytics tool
  * contributors, commits, issues, PRs, forks, stars, etc over time
  * Each information has a definition
  * Next to this there is a list of computed information, like contributor dependency (eg bus factors); organization dependency, active days, contribution outside working hours, etc, along with leaderboards per each metric, geographic distribution, etc.
  * Definitions are well rounded - eg working with issues are considered contribution as well; so it will be a superset of the information you can get natively from GitHub 
  * It has the option to include the mailgroups as well showing relevant data based on individual, organization, etc. ; this is something for the TOC to decide whether there is value to ask Kieran to add the groups
  * Multiple ways to see project velocity
  * @eminty69 sees this as a possible tool to replace l.finos.org or the popup details of the landscape
  * Separate information about project health (openSSF), and contributor diversification over time
  * Some open questions like "how affiliation is tracked?", Kieran should get back to us sometime in Q1 with the new UX to continue the discussions
  * Companies can use it for their own purposes 
  * Action item: Get @mcderk back in Feb/March to talk about progress
@eminty96
 * Many of Kieran's tooling is useful for the Liaison Strategy; on the other hand, we want to avoid the projects feeling Big Brother is watching over
 * We should be better in area definitions, eg it is not Morphir and/or Legend, it should be generally about 'reg tech' as an area, figure out how project gravitate to each other
 * Two different representations of projects (by Colin and Rob) existed before
 * Action item: divide projects, talk to maintainers
 * Action item: set up project matrix to see collaboration opportunities; set up a dedicated session for this with Juan's help
@chris-twiner
 * Reasonable metrics - eg an active project but one maintainer might be an issue
 * Publishing results should be after the Liaison is already in affect
 * Action item: should we have more elaborate design for project lifecycle
 * Action item: Juan to set up mtg on this
@jgavronsky
 * TOC OKR overview and short discussion about 2025
@psmulovics
 * Asking everyone to check out #166 for next year's *proposed* schedule

**Comment by eddie-knight** [comment]
Created #167 to collect next steps and any ongoing discussion about the Project Lifecycle topic
