### ISSUE TITLE
2024 Dec 18 - Technical Oversight Committee Meeting Minutes

### ISSUE THREAD

**Issue by psmulovics** [finos/technical-oversight-committee#169]
## Zoom Info
- Time: 12pm EST
- Meeting link: [https://zoom.us/j/93181085065](https://zoom.us/j/93181085065?pwd=cys5NHRqcWFZaG9qdlB4SlR2Zjh3UT09)
- Meeting id: 931 8108 5065
- Call-in: Find your local number https://zoom.us/u/abk6zPS0y5

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Backlog review - https://github.com/orgs/finos/projects/39
- [x] Reminder on #166
- [x] Discuss #168 w/ @eminty69 
- [x] Discuss #167 w/ @chris-twiner 
- [ ] Discuss #170 w/ @psmulovics 
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes
- [ ] ...
- [ ] ...
- [ ] ...

## Action Items
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by chris-twiner** [comment]
Chris Twiner

**Comment by rocketstack-matt** [comment]
Matthew Bain / Morgan Stanley

**Comment by DamianReeves** [comment]
Damian Reeves / Capital One

**Comment by eminty69** [comment]
Elspeth Minty / RBC Capital Markets

**Comment by opoupeney** [comment]
Olivier Poupeney / FINOS

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by mindthegab** [comment]
Gab / FINOS

**Comment by psmulovics** [comment]
* Discussing #166
 * Discussion on timing for central timezone and asia
 * Agreed to merge it for now and would revisit the 50% rule in April
 * DECISION: We merged and Juan will make the changes on the calendar (public, private, new zoom codes as needed, etc.)
 * ACTION: @psmulovics to add this to the April meeting as a agenda item
* @eminty69 discussing #168
 * Have clear understanding who is the maintainers
 * Have clear understanding whether and how maintainers are engaged
 * What is the roadmap of a project - where they are, and where they are heading
 * What is needed from FINOS to support the project - should it be a '5 on the community call, an OSFF session, etc
 * Not every project today available is necessarily would need to be continued to be hosted by FINOS (other foundations, etc., too long being incubated, etc.); we can solve this easily by only showing active projects on websites, etc till we arrive to decisions
 * Maintainers needs to understand when they get to archival threshold - liaisons would help each project maintainer to understand their situation
 * Karl is happy to 'liaison the liaisons'
 * Although all projects would be eventually covered by TOC, we would start with the focus on the "strategic initiatives" as a start
 * Discussion about whether the maintainers should be more participation in filling out the updates (push vs pull model); but we want to have the personal touch and relationship
* @chris-twiner discussing #167
 * Link shared: https://community.finos.org/docs/governance/Software-Projects/project-lifecycle
 * Right now 3 statuses, which is different than CNCF or the rest of LF
  * Definition of Active is missing some of the common sense things (like having docs), and some projects which are Active not meeting the existing criteria for 'major v1' release
  * No safe-bet indication, Active projects can have KPD's (like FDC3, CDM)
 * No indication of overall health - while LFX dashboards provide rich info, not 'at a glance' view we would need
 * **Proposal**
  * Separate maturity from status; probably need to add finos-labs here too?
  * Define maturity along governance and growth lines (like CNCF says sandbox -> incubator -> graduated)
  * Introduce project status like repostatus.org, eg Unstable and Stable. This should differentiate the different archive states (eg dev is done and support is best efforts VS something is like really archived)
  * Longer term to create a statistics/health view of the project; working with LFX on the 'at a glance' one plane view with GH embeddable information on additional information like code coverage, code activity, community participation, download count, vulnerability response time, etc. This would help a lot the TOC seeing the % shifts/absolute value changes/etc.
 * ACTION: to set up working group to discuss this and create PRs
* Discussing #170
 * Agreement that we need to figure this out - a lot of details to be hashed out with this as we have projects graduated from labs, projects just having releases with being SIGs, etc.

**Comment by arroyo** [comment]
John Arroyo / Citi

**Comment by arroyo** [comment]
Where can I find the list of 24 projects that need to be assigned? Also should we comment on this issue or https://github.com/finos/technical-oversight-committee/issues/168?
