### ISSUE TITLE
[TOC Candidacy] Jamie Slome

### ISSUE THREAD

**Issue by JamieSlome** [finos/technical-oversight-committee#86]
## Affiliation

I'm the Operations Lead for @Citi OSPO.

## Bio

Jamie Slome joined Citi in November 2022 as the Operations Lead for Citi’s Open Source Program Office (OSPO). He is responsible for implementing developer tooling that supports Citi’s open source contribution initiatives and spearheads the expansion of the Open Source Program Office.
 
Prior to this, he co-founded and served as Chief Technology Officer at [huntr.dev](https://huntr.dev/) ([recently acquired by ProtectAI](https://uk.finance.yahoo.com/news/protect-ai-acquires-huntr-launches-130300083.html)) – the go-to vulnerability management and responsible disclosure platform for world-renowned open source libraries including [vim](https://www.vim.org/), [draw.io](http://draw.io/) and [nuxt.js](https://nuxt.com/). He also served as a product owner and security engineer at BT Security, developing threat intelligence and data insight solutions for BT’s global Security Operation Centre (SOC) network. 
 
Jamie graduated from King’s College London with a bachelor’s degree in Computer Science and Artificial Intelligence. Subsequently, he authored and published [“A Lane Merge Coordination Model for a V2X Scenario”](https://ieeexplore.ieee.org/document/8801987); a paper on autonomous vehicles, 5G and edge-cloud computing in collaboration with Ericsson, Bosch, Volvo and King’s College London. He presented and demonstrated his work at Mobile World Congress alongside Centre Tecnologic de Telecommunications de Catalunya (CTTC).

## Reason for candidacy

Lead maintainer of [Git Proxy](https://github.com/finos/git-proxy) ⚡

**Comment by ColinEberhardt** [comment]
As the current TOC chair, I just want to say thank you for taking the time to put yourself forward as a candidate. 🙏

**Comment by JamieSlome** [comment]
@maoo - please can you re-open this issue?

**Comment by maoo** [comment]
This first round of voting closed today; next and round is scheduled for 6 September 2024.

**Comment by maoo** [comment]
Thanks for your candidacy @JamieSlome ! We've started the voting today, and we are expecting to know the results by next week; we will keep you posted.

**Comment by TheJuanAndOnly99** [comment]
Congratulations @JamieSlome, you've been selected to be part of the FINOS TOC. Looking forward to meeting at the next TOC call. You should have already gotten an email from me. If you have not please email help@finos.org! Thank you!
