### ISSUE TITLE
[TOC Candidacy] Matthew Bain

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/technical-oversight-committee#87]
### Affiliation
Morgan Stanley

### Bio
Matthew Bain leads Architecture, DevOps and Modernization for Securities Finance Technology at Morgan Stanley. He joined the firm in 2013 and has held various roles across the Institutional Securities Technology division including previously leading Cash Management Technology and Securities Lending Trading Technology. Matthew also sits on a number of firmwide governance and oversight committees.

Matthew studied Computer Science at Durham University and has worked in Technology across the Finance industry for over 20 years. Prior to Morgan Stanley, Matthew held positions at a number of other large financial institutions covering multiple asset classes and technology functions including Asset & Wealth Management, Equities Program Trading and Client & Regulatory Reporting. 

Matthew is passionate about improving software development practices and driving speed, agility and resilience through a radical focus on process automation.

### Reasons for Candidacy 
Matthew co-leads the [DevOps Automation SIG](http://devops.finos.org/) with a specific focus on the [Architecture as Code Working Group](https://devops.finos.org/docs/working-groups/aasc/). Matthew has contributed to the [TraderX Trading Simulator](https://github.com/finos-labs/traderX)

**Comment by ColinEberhardt** [comment]
As the current TOC chair, I just want to say thank you for taking the time to put yourself forward as a candidate. 🙏

**Comment by maoo** [comment]
Reopening as requested by @rocketstack-matt

**Comment by maoo** [comment]
Congratulations @rocketstack-matt  , you've been selected to be part of the FINOS TOC. Looking forward to meeting tomorrow for your first TOC call.
