### ISSUE TITLE
[TOC Candidacy] Paula Paul

### ISSUE THREAD

**Issue by PaulaPaul** [finos/technical-oversight-committee#88]
Affiliation: 
[Greyshore](https://www.greyshore.com)

Bio:
Paula ([LinkedIn](https://www.linkedin.com/in/paulapaul), [GitHub](https://github.com/PaulaPaul)) has grown as a software engineer and technologist since her career began programming for IBM in the early 1980's. She moved from mainframes, to AIX and Posix, to Windows desktops, servers and databases, to Open Source, cloud adoption, infrastructure as code, and more to come. She is passionate about serving, and growing, the Open Source community.

Context and goals for self-nomination:
Paula formerly served as a Field CTO with NearForm and, along with her engineering team, championed NearForm's Linux Foundation and Gates Foundation relationships. She is the owner and Distinguished Engineer with Greyshore Associates,  a board member with the [OpenJS Foundation](https://openjsf.org/) and participates in the OpenJS Foundation's Cross Project Council and other working groups. Paula belongs to FINOS / Legend in GitLab and the FINOS organization in GitHub as a maintainer of the FINOS Accessibility Theme Builder Project. Paula enjoys speaking about foundation work at conferences around the globe on behalf of their Linux Foundation work to raise awareness of open source, and grow the community.

In addition, Paula has spoken in the Open Source track of the Grace Hopper Celebration, and served on committees for the Grace Hopper Celebration's Open Source Day multiple times; she served as Co-Chair for this years OSD hackathon. Paula's team won an award at the FINOS GAAD hackathon for their work on Discover's Accessibility Theme Builder, and hosted the Accessibility Theme Builder as a step towards that project's hosting with  FINOS. Her team served as mentors for the Theme Builder and other open source projects during the Grace Hopper OSD event. 

Paula is a champion for diversity and inclusion through her Linux Foundation work and hopes to bridge her Linux Foundation contributions to more hackathons and project sponsorships with the AnitaB.org and Gates Foundations. Paula's team is actively supporting the [Mojaloop Foundation](https://mojaloop.io/) and their work on Inclusive, Equitable Financial Services For All, and hopes to bridge this work to FINOS for cross-foundation collaboration.

**Comment by ColinEberhardt** [comment]
As the current TOC chair, I just want to say thank you for taking the time to put yourself forward as a candidate. 🙏

**Comment by Neetuj** [comment]
Impressive!

**Comment by ColinEberhardt** [comment]
Of course - thanks @PaulaPaul 

@maoo I don't have permission to re-open, are you able to do this?

**Comment by ColinEberhardt** [comment]
@maoo my mistake, yes I do - re-opened!

**Comment by maoo** [comment]
Congratulations @PaulaPaul  , you've been selected to be part of the FINOS TOC. Looking forward to meeting tomorrow for your first TOC call.
