### ISSUE TITLE
TOC attending OSFF

### ISSUE THREAD

**Issue by TheJuanAndOnly99** [finos/technical-oversight-committee#90]
Please drop a comment if you plan on attending OSFF.

**Comment by opoupeney** [comment]
Attending

**Comment by eminty69** [comment]
Attending

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum @ Morgan Stanley attending

**Comment by ColinEberhardt** [comment]
I'll be there 👍

**Comment by eteridvalishvili** [comment]
Hi @caradelia @ColinEberhardt @opoupeney @stephengoldbaum Happy to hear that you will be attending OSFF! I understand there were some discussions about organizing an in-person meeting that could be part of the project meetings series. I wanted to reach out to discuss the possibility of also having a TOC table at [OSFF](https://events.linuxfoundation.org/open-source-finance-forum-new-york/). We have a number of project tables, and this would be a part of them. If you are available to either have an in-person meeting or staff a TOC booth on the day of the conference so people can come and ask any questions they may have and learn more, please let me know!

**Comment by stephengoldbaum** [comment]
Individual meeting would be good. I can man a table part time if needed.

**Comment by ColinEberhardt** [comment]
A table would be a good idea, I can probably man it from time-to-time. For a TOC meetup, given that various people have talks and other duties, should we aim to meet up in a break? What about 3:10pm?

**Comment by eminty69** [comment]
That time works for me.  I can do a table part time also but I've another project table to be at also.

**Comment by opoupeney** [comment]
My initial idea for a TOC table was to see this as a support to FINOS (our main duty actually), by being present on the table at a dedicated time (like coffee breaks or lunch breaks) and help visitor giving an overview of FINOS landscape & answering questions about FINOS projects and/or guide them to the appropriate project booth / owner. FINOS could announce our presence like "Meet the TOC experts at coffee/lunch breaks who can guide you in understanding the FINOS landscape".
Wdyt?

**Comment by eteridvalishvili** [comment]
Hi @opoupeney @eminty69 @ColinEberhardt @stephengoldbaum @caradelia I hope you are doing well! I wanted to follow up on my email regarding the TOC booth. Please let me know if you have any questions about logistics for the day.
