### ISSUE TITLE
[TOC Candidacy] Eddie Knight

### ISSUE THREAD

**Issue by thiswayman** [finos/technical-oversight-committee#91]
Affiliation: Sonatype

Bio: Eddie Knight has been a technical leader in organizations ranging from financial services to software security, enabling him to gain the wealth of experience and insight that he brings as a speaker, author, and strategist. In addition to his role leading the Open Source Program Office at Sonatype, Eddie serves as maintainer of the FINOS Compliant Financial Infrastructure project, is the lead organizer for the CNCF Cloud Native Security Slam, and is a maintainer for the OpenSSF Security Insights Specification.

Reasons for Candidacy: Sonatype believes that as part of the FINOS TOC, Eddie Knight will be able to uniquely elevate the financial open source ecosystem by combining insights gained from his work within FINOS, CNCF, and OpenSSF.

**Comment by ColinEberhardt** [comment]
Hi Eddie! As the current TOC chair, I just want to say thank you for taking the time to put yourself forward as a candidate. 🙏

**Comment by eddie-knight** [comment]
Thanks @thiswayman and @ColinEberhardt!

**Comment by eddie-knight** [comment]
@maoo, please reopen this candidacy issue.

In addition to the previous notes from Jeff, I am now a Co-chair for CNCF's TAG Security, part of the steering committee for the Common Cloud Controls project, and a FINOS Ambassador. I have also recently begun helping to design the implementation and partnerships strategies for the emerging Supply Chain Security Strategic Initiative.

**Comment by maoo** [comment]
Congratulations @eddie-knight  , you've been selected to be part of the FINOS TOC. Looking forward to meeting tomorrow for your first TOC call.
