### ISSUE TITLE
[TOC Candidacy] Sam Marland

### ISSUE THREAD

**Issue by sammarland-rh** [finos/technical-oversight-committee#92]
**Affiliation**: Red Hat

**Bio**: Sam currently leads the UK Financial Services and Insurance technical presales team at Red Hat. Before taking this leadership role, he was a Principal Solution Architect working closely with the two largest retail banks in the UK to help them adopt a broad range of open source software. He has a passion for applying iterative methodologies to gain improvements. Sam has taken his background in delivering Agile and DevOps projects into the Finance sector and successfully used these to help customers in their journeys. He has been involved in projects, including supporting a large retail bank to adopt open source hybrid cloud technologies to accelerate value creation. Sam has also worked with customers to understand better and apply open source, inner source and DevSecOps principles and practices to their software development functions.

Sam supports open source, and open collaboration and thinks they are the best way to solve some of the biggest challenges facing the Financial Services industry. One of these challenges is how financial institutions manage risk whilst harnessing cloud technology. Sam has been involved in building Red Hat’s point of view on cloud concentration risk and stressed exit. With this work in mind, he is particularly interested in the recently announced Common Cloud Controls Project, which offers a realistic solution to large institutions' challenges.  

The team that Sam is responsible for is also working with a range of FINOS members on inner-source projects that have been featured in recent FINOS conferences.

As well as his current role, Sam is currently studying part-time for his MBA at the University of Exeter Business School and is expected to complete his studies at the end of 2024. 

**Reasons** for candidacy: Member

**Comment by ColinEberhardt** [comment]
As the current TOC chair, I just want to say thank you for taking the time to put yourself forward as a candidate. 🙏
