### ISSUE TITLE
[TOC Candidacy] Damian Reeves

### ISSUE THREAD

**Issue by DamianReeves** [finos/technical-oversight-committee#93]
## Affiliation
Capital One

## Bio

Damian Reeves is a Distinguished Engineer at Capital One with a background in implementing solutions across financial services firms including Morgan Stanley, AllianceBernstein, Jennison Associates, and Och-Ziff Calital Management. 
He is currently focused on using domain specific languages and programming language theory to enhance the configurability of system at Capital One.

His passion is for functional programming, functional and domain driven design, and using domain specific languages to translate business requirements into software. While at Morgan Stanley, he was involved in taking Morphir from an in-house developed tool to a FINOS project. Damian is one of the maintainers of Morphir and has been a key contributor in initiatives to expand Morphir across language ecosystems via projects like `morphir-scala` and `morphir-dotnet`.  Damian is a believer in open source software and has contributed to a variety of projects, most recently to Morphir, various ZIO community projects as well as plugins for the mill build tool. He has also been an advocate for open source in the enterprise setting and has worked with Open Source Program Offices, both at Capital One and at Morgan Stanley.

He has been a speaker at Functional Scala (2020, 2021, and 2022) and the Open Source in Finance Forum, as well as a speaker and panelist at Zymposium a community meetup sponsored by ZIO contributors and Ziverge.

## Reasons for Candidacy

Damian is one of the maintainers of [Morphir](https://github.com/finos/morphir) and leads the development of Morphir initiatives in [Scala](https://github.com/finos/morphir-scala) and [.NET](https://github.com/finos).

**Comment by ColinEberhardt** [comment]
As the current TOC chair, I just want to say thank you for taking the time to put yourself forward as a candidate. 🙏
