### ISSUE TITLE
[TOC Candidacy] Peter Smulovics

### ISSUE THREAD

**Issue by psmulovics** [finos/technical-oversight-committee#94]
### Affiliation

Morgan Stanley

### Bio

Peter Smulovics leads Windows and .NET Development Practices, and Metaverse and Spatial Computing Development Practices at Morgan Stanley. Joined in 2010 after spending a decade at Microsoft working on .NET, Visual Studio.NET, Dynamics, Azure and more. Peter leads and participates in various internal and external Hackathons (FSI Autism Hackathon, Accessibility Hackathon, Generative AI Hackathon, etc.), and joins the work of various firmwide committees.

He is a publicist for IDG, Architecture Journal, Wrox and more, and returning presenter at external events like TechEd, DevDays, TechReady, Agile DevCon, TechNet, and keynoting events like [Meta's Future of Work event](https://dotneteers.net/the-future-of-work-at-meta-showcasing-the-next-phase-of-xr/) or presenting at [Women in IT's FullCIRCLE](https://dotneteers.net/being-a-small-arc-in-a-fullcircle/) event. 

He is a founder member of AgileAlliance, Architecture Forum, Architect Academy and .NET Forum, current or previous technical lead on several OSS projects like NHibernate, NVelocity and more. He is contributing to various OSS projects in the Microsoft and .NET space. Has Microsoft, Ariba, JBoss, SiteCore certifications, and also providing training on several technologies. Working in IT since 1995, has project experience in different fields (FMCG, public, financial, energy, telecom, pharmaceutical, mobile, music, and security).

Peter runs a technical / soft skills blog at https://dotneteers.net, where he writes a lot about OSS and other passions of his.

### Reasons for Candidacy

Peter co-leads [Open Source Readiness](https://osr.finos.org) and [Emerging Technologies](https://zenith.finos.org) SIGs, and actively participates in the work of the [FDC3 SIG](https://fdc3.finos.org). Peter is also working on bringing [Big Boost Mondays](https://tg.zngly.com) over to North America.

**Comment by ColinEberhardt** [comment]
As the current TOC chair, I just want to say thank you for taking the time to put yourself forward as a candidate. 🙏
