### ISSUE TITLE
[TOC Candidacy] Tim Paine

### ISSUE THREAD

**Issue by timkpaine** [finos/technical-oversight-committee#95]
**Affiliation**: Point72

**Bio**: I am currently a developer at Point72. I previously worked at IEX and JP Morgan. I have helped lead OSS efforts at these companies, most often as a lead maintainer of one or more of the first projects to be open sourced. I maintain and contribute to numerous open source projects, with many projects in the scientific python ecosystem. I am a core maintainer of [perspective](https://github.com/finos/perspective), [jupyterlab-templates](https://github.com/finos/jupyterlab_templates), [regular-table](https://github.com/finos/regular-table ), and [ipyregulartable](https://github.com/finos/ipyregulartable), totaling over 7,000 GitHub stars under the FINOS organization. I am also an adjunct professor in the Computer Science department at Columbia University, where my classes include [Open Source Development](https://www.cs.columbia.edu/~paine/4995/). 

**Reasons for candidacy**: Lead maintainer of several projects, hoping to drive advancement for existing and future FINOS projects and assist other members in adoption of FINOS projects.

**Comment by ColinEberhardt** [comment]
As the current TOC chair, I just want to say thank you for taking the time to put yourself forward as a candidate. 🙏
